// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqkzybnagdobradtlwpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa3p5Ym5hZ2RvYnJhZHRsd3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDQ4NDAsImV4cCI6MjA2MTkyMDg0MH0.pr404v2XHGfdeo_ngSCnt4BOD-sUuzbpjktxYaR_4_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);